version: '2'
services:
    jhipster-app:
        image: jhipster
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://jhipster-mariadb:3306/jhipster
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipster-mariadb:
        extends:
            file: mariadb.yml
            service: jhipster-mariadb
